### PR TITLE
Generated files #28

### PR DESCRIPTION
**Pull request by tschuchortdev**
@ZacSweers Does this resolve your issue #28 ?

### CODE REVIEW

**Comment by ZacSweers** [comment]
Yep! I do think it'd be better to differentiate between generated files and output files, but this is a good start.

**Comment by tschuchortdev** [comment]
Yes, I did it like this because I couldn't change the name for backwards compatibility and I think including generated sources captures the meaning of the name more closely. You can still get only the final output files by traversing the `Result::outputDirectory` or by looking at the parent folders of the files in the list. Or if nothing else helps you can always just look at the respective directory properties of `KotlinCompilation` directly. The list in `KotlinCompilation.Result` is more of a convenience thing.

**Comment by tschuchortdev** [comment]
The changes should be available in the SNAPSHOT repository by the end of the day.

**Comment by ZacSweers** [comment]
Would it be possible to add some helper extension functions that filter by
file type? Or generation source (kotlinc, kapt, etc).

**Comment by tschuchortdev** [comment]
Probably, but that feels wrong to me. The best thing would be to tag every file in the list with its origin, but that breaks backwards compatibility, which I would like to avoid. Maybe I should add separate properties for the different file "types"? Like `sourcesGeneratedByAnnotationProcessor`, `compiledClassFiles`, `compiledResourceFiles`, `generatedStubFiles`, etc.

**Comment by ZacSweers** [comment]
Why does it feel wrong? This is how the Java compile-testing project works.
In fact I don't think I've ever seen a test using that checked generated
files for anything other than generated sources.

**Comment by tschuchortdev** [comment]
Because then that extension function would apply to all file lists even though it doesn't make sense to use it there. In a sense we lose type safety (and pollute the namespace). 

Such an extension function would look something like this:

```Kotlin
fun List<File>.onlySourcesGeneratedByAnnotationProcessor() = filter {
    it.parent?.parent?.name == "kapt" && it.parent?.name in setOf("sources", "kotlinGenerated")
}
```

Not to mention that the directory names are concerns of the `KotlinCompilation` class that we would leak out.

Or do you mean extension functions on `KotlinCompilation.Result`? That's basically the same as adding extra properties.

**Comment by ZacSweers** [comment]
Yeah I mean on the result. It is, but it wouldn't come at the expense of backward compatibility. I'm willing to argue that 95% of users exclusively use `generatedSources()` if it existed. I can't think of any time I've used compile-testing to check for a class file since I'm not testing the compiler. Maybe that changes with compiler plugins support, but for annotation processors you absolutely are usually just testing generated sources.

**Comment by tschuchortdev** [comment]
> It is, but it wouldn't come at the expense of backward compatibility.

Why would additional properties affect backwards compatibility in contrast to extension functions? The two are practically identical. 

I can add the extra properties/functions for filtering tomorrow.

**Comment by ZacSweers** [comment]
They wouldn't, that was my point :). I was only proposing adding them, not replacing the existing `generatedFiles` property. Sorry for any misunderstanding

**Comment by tschuchortdev** [comment]
On another note: What are you testing on the generated sources? Isn't it better to load the compiled class files and then use reflection on them to test the implementation?

**Comment by ZacSweers** [comment]
Not at all! Especially with kotlin, that would require reading metadata and reconstructing the entire object. We want to just do something similar. Here's an example test we plan to enable with this: https://github.com/square/moshi/blob/master/kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessorTest.kt#L353-L375

Where the body of the file (the `// TODO implement this`) block would just be the expected sources. That's far simpler and sufficient for our needs for source testing. This is how compile-testing is often used as well. Example: https://github.com/rharter/auto-value-gson/blob/master/auto-value-gson/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessorTest.java

**Comment by tschuchortdev** [comment]
I don't really get what you're saying about metadata. Isn't that all handled by the kotlin-reflect library? Or are you worried about performance of the unit tests?

Comparing the generated source to a string just seems very brittle to me. One extra whitespace and your test will fail.

**Comment by ZacSweers** [comment]
We would have to load all of the bytecode into memory and use reflection.
It's much easier at a glance to read sources of what it's expected to look
like, and we only use it sparingly for cases where we care about source
being structured a certain way.

**Pull request merged**
