### PR TITLE
Create parent directories of nested SourceFile

### PR DESCRIPTION
**Pull request by pranjalvachaspati-toast**
Currently, `createNewFile()` fails if you have a `SourceFile` in a directory, since it can't create the owning directory.

Calling `mkdirs()` on the parent directory fixes this, and has no effect if the path already exists.

### CODE REVIEW

**Comment by pranjalvachaspati-toast** [comment]
This fixes Issue #340.

**Comment by pranjalvachaspati-toast** [comment]
@tschuchortdev please let me know if this PR needs anything!

**Comment by jisungbin** [comment]
Hi @tschuchortdev, I need this feature. Can you review this PR?

**Comment by tschuchortdev** [comment]
Thanks for this PR! I'm sorry I didn't get to it sooner. Your work is appreciated and will be in the next release, which I'm about to start.

**Pull request merged**
