### PR TITLE
Add 'withCompilation' to enable full compilation with symbol processors. 

### LINKED ISSUE #191: Class files are not generated
I'm using this library to test KSP processor and I need to access class files generated by Kotlin compiler (compiled original source files and compiled generated source files). 
It turns out that compilation successfully completes but classes directories (root and in ksp subdirectory) are empty.

### PR DESCRIPTION
**Pull request by bennyhuo**
This also fixes #191.

### CODE REVIEW

**Comment by bennyhuo** [comment]
Btw, it does not add the ksp generated sources to the compilation automatically by setting this option to true. Maybe we should do some additional work in the core library on ksp sources similar with the kapt sources to make this completely work.

**Comment by tschuchortdev** [comment]
Hi, thanks for your PR. Why did you close it again? It looks like a valuable addition, so I'd like to merge it.

**Comment by bennyhuo** [comment]
I find that it is not enough to make the ksp compilation work. The problem is that it does compile the sources with the option enabled but the generated sources by symbol processors do not be compiled in the same invokation.

So I move back to the workaround by compiling with symbol processsors to generate files first and then compiling the sources with the generated sources together.....

**Comment by bennyhuo** [comment]
[Here](https://github.com/bennyhuo/kotlin-compile-testing-extensions/blob/master/kotlin-compile-testing-extensions/src/main/kotlin/com/bennyhuo/kotlin/compiletesting/extensions/module/KotlinModule.kt#L48-L48) is the workaround.

**Comment by tschuchortdev** [comment]
I see, but this PR only adds an extension property with the default still set to `false` so I think we can merge it and people can decide if they want to use it or not (even if it doesn't solve the problem). 

To really solve all the problems with KSP once and for all, I suppose we would need a flexible extension system similar to Gradle tasks, but I want to keep the library as simple as possible. Maybe it is time that I move the KSP stuff into the core library (since KAPT is practically deprecated) and that would make things a lot easier.

**Comment by bennyhuo** [comment]
That would be great!

**Pull request merged**
