### PR TITLE
Update to Kotlin 1.8.0

### LINKED ISSUE #336: Support Kotlin 1.8
👋 I'm currently testing out Kotlin 1.8 in [Anvil](https://github.com/square/anvil) and running into test failures due to an API that was removed but is currently used by kotlin-compile-testing. Are there any plans to add support / a new release for this soon?

Additional details:
The API removal was for `singleModule` in `K2JVMCompilerArguments` as[ part of this commit](https://github.com/JetBrains/kotlin/commit/a76de140265a4fdd03fb9c7b642a9cdef7c9c179). This API is accessed in [`KotlinCompilation` line 359](https://github.com/tschuchortdev/kotlin-compile-testing/blob/master/core/src/main/kotlin/com/tschuchort/compiletesting/KotlinCompilation.kt#L359) currently which gets executed for nearly all Anvil compiler tests. When this happens, the following error is produced:
```
'void org.jetbrains.kotlin.cli.common.arguments.K2JVMCompilerArguments.setSingleModule(boolean)'
java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.cli.common.arguments.K2JVMCompilerArguments.setSingleModule(boolean)'
	at com.tschuchort.compiletesting.KotlinCompilation$commonK2JVMArgs$1.invoke(KotlinCompilation.kt:359)
	at com.tschuchort.compiletesting.KotlinCompilation$commonK2JVMArgs$1.invoke(KotlinCompilation.kt:300)
	at com.tschuchort.compiletesting.AbstractKotlinCompilation.commonArguments(AbstractKotlinCompilation.kt:133)
	at com.tschuchort.compiletesting.KotlinCompilation.commonK2JVMArgs(KotlinCompilation.kt:300)
	at com.tschuchort.compiletesting.KotlinCompilation.stubsAndApt(KotlinCompilation.kt:472)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:655)
	at com.squareup.anvil.compiler.internal.testing.AnvilCompilation.compile(AnvilCompilation.kt:186)
	at com.squareup.anvil.compiler.internal.testing.AnvilCompilation.compile$default(AnvilCompilation.kt:174)
	at com.squareup.anvil.compiler.internal.testing.AnvilCompilationKt.compileAnvil(AnvilCompilation.kt:249)
	at com.squareup.anvil.compiler.internal.testing.AnvilCompilationKt.compileAnvil$default(AnvilCompilation.kt:211)
	at com.squareup.anvil.compiler.dagger.ProvidesMethodFactoryGeneratorTest.compile(ProvidesMethodFactoryGeneratorTest.kt:3476)
	at com.squareup.anvil.compiler.dagger.ProvidesMethodFactoryGeneratorTest.compile$default(ProvidesMethodFactoryGeneratorTest.kt:3471)
	at com.squareup.anvil.compiler.dagger.ProvidesMethodFactoryGeneratorTest.a factory class is generated for an internal provider method with a mangled name in a companion object(ProvidesMethodFactoryGeneratorTest.kt:834)
	...
```

If you need an example for testing, you can pull down Anvil, checkout branch [joel.test-kotlin-1-8](https://github.com/square/anvil/tree/joel.test-kotlin-1-8), and then run 
```./gradlew :compiler:test  --no-build-cache --no-daemon -Psquare.kotlinVersion=1.8.0-RC-268```

### PR DESCRIPTION
**Pull request by 3flex**
Closes #336 
Closes #333 
Closes #328
Closes #329

### CODE REVIEW

**Comment by 3flex** [comment]
Needs an update to 1.8.10.

@tschuchortdev I'm sorry to ping you directly, but is there a chance we could get this reviewed and merged? I know there are a few projects waiting on it.

Please let me know, thanks.

**Comment by sgammon** [comment]
have to halt testing until this is fixed :(

**Comment by Bencodes** [comment]
@tschuchortdev are you able to help land this PR to unblock codebases from adopting Kotlin 1.8?

**Comment by Bencodes** [comment]
Thanks for landing this and cutting a new release @tschuchortdev! Much appreciated!

**Comment by tschuchortdev** [comment]
I should be the one thanking @3flex and @ZacSweers for their help in supporting the new compiler version.

**Pull request merged**
