### PR TITLE
Support Kotlin 1.8.21

### LINKED ISSUE #379: Support Kotlin 1.8.21
Hello 👋 

Awesome work on the library! By any chance there will be a new version released soon that supports Kotlin v1.8.21? 

I tried updating it ([link](https://github.com/dariuszkuc/kotlin-compile-testing/commit/c6f8742aa4c8a3c79b6b5f32eaf0a1185efdb855)) but sadly there is some change in behavior in v1.8.20 that breaks JS compiler. Nothing jumps out from the [release notes](https://kotlinlang.org/docs/whatsnew1820.html) - they did add alpha support for new JS IR compiler but that "shouldn't" affect the legacy compiler.

After updating to v1.8.20+ JS compilation fails asking to set some IR properties (`-ir-output-dir` and `-ir-output-name`). I tried updating the default [`KotlinJsCompilation#jsArgs()`](https://github.com/tschuchortdev/kotlin-compile-testing/blob/master/core/src/main/kotlin/com/tschuchort/compiletesting/KotlinJsCompilation.kt#L75-L95) args to include those but that didn't work either, i.e. I added the following

```kotlin
args.moduleName = "KCT"
args.outputDir = outputDir.toString()
```

With the above JS compilation runs but does not produce any outputs.... Any help would be appreciated!

### PR DESCRIPTION
**Pull request by tschuchortdev**
Closes #379

### CODE REVIEW

**Comment by dariuszkuc** [comment]
👋 any luck with debugging windows issue on this?

**Comment by BoD** [comment]
Just opened a PR to support 1.9.0: #388

**Comment by dariuszkuc** [comment]
@tschuchortdev by any chance can we release it as is? 

I tried building this on my Windows 10 machine and it worked fine using JDK 11/17 from IntelliJ, command prompt, powershell and WSL2. There might be an issue with Windows 11 but don't have a local machine to test it out.

**Comment by tschuchortdev** [comment]
Superseded by release for 1.9.24

**Pull request closed without merging**
